services:
  response-generator-gemini:
    env_file: 
    - setup.env
    - ./modules/response-generator-gemini/config.env
    expose: 
    - 5000
    build: ./modules/response-generator-gemini/.
    volumes:
    - ./modules/response-generator-gemini/app:/app
    depends_on: []