services:
  front-end-intervention:
    expose: 
    - 5000
    env_file: 
    - setup.env
    - ./modules/front-end-intervention/config.env
    build: ./modules/front-end-intervention/.
    ports: 
    - "9000:9000"
    volumes:
    - ./modules/front-end-intervention/backend:/backend
    - ./modules/front-end-intervention/frontend:/frontend
    depends_on:
    - knowledge-demo
    - redis